package domain

import (
	"time"

	"gorm.io/gorm"
)

// FinancialProfile represents user's financial information
type FinancialProfile struct {
	ID                uint    `gorm:"primaryKey"`
	UserID            uint    `gorm:"uniqueIndex;not null"`
	MonthlyIncome     float64 `gorm:"not null;default:0"`
	FixedExpenses     float64 `gorm:"not null;default:0"`
	InvestmentRatio   float64 `gorm:"not null;default:0.1"` // 10% default
	InvestmentAmount  float64 `gorm:"not null;default:0"`   // Fixed amount (alternative to ratio)
	UseRatio          bool    `gorm:"not null;default:true"` // Use ratio or fixed amount
	RiskTolerance     string  `gorm:"type:varchar(20);not null;default:'moderate'"`
	InvestmentGoals   string  `gorm:"type:text"`
	TimeHorizon       string  `gorm:"type:varchar(20)"` // short, medium, long
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         gorm.DeletedAt `gorm:"index"`
}

// Portfolio represents user's investment portfolio
type Portfolio struct {
	ID        uint      `gorm:"primaryKey"`
	UserID    uint      `gorm:"not null"`
	Name      string    `gorm:"type:varchar(100);not null"`
	Holdings  []Holding `gorm:"foreignKey:PortfolioID"`
	TotalValue float64  `gorm:"not null;default:0"`
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Holding represents a single asset holding in portfolio
type Holding struct {
	ID          uint    `gorm:"primaryKey"`
	PortfolioID uint    `gorm:"not null;index"`
	AssetType   string  `gorm:"type:varchar(20);not null"` // crypto, stock, forex
	Symbol      string  `gorm:"type:varchar(20);not null;index"`
	Quantity    float64 `gorm:"not null"`
	AvgBuyPrice float64 `gorm:"not null"`
	CurrentPrice float64 `gorm:"not null;default:0"`
	TotalValue  float64 `gorm:"not null;default:0"`
	PnL         float64 `gorm:"not null;default:0"`
	PnLPercent  float64 `gorm:"not null;default:0"`
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// MarketData represents time-series price data
type MarketData struct {
	ID         uint      `gorm:"primaryKey"`
	Symbol     string    `gorm:"type:varchar(20);not null;index:idx_symbol_time"`
	AssetType  string    `gorm:"type:varchar(20);not null"` // crypto, stock, forex
	Price      float64   `gorm:"not null"`
	Volume     float64   `gorm:"default:0"`
	High24h    float64   `gorm:"default:0"`
	Low24h     float64   `gorm:"default:0"`
	Change24h  float64   `gorm:"default:0"`
	MarketCap  float64   `gorm:"default:0"`
	Timestamp  time.Time `gorm:"not null;index:idx_symbol_time"`
	Source     string    `gorm:"type:varchar(50)"` // binance, yahoo, coingecko
	CreatedAt  time.Time
}

// Signal represents trading signals generated by advisory engine
type Signal struct {
	ID          uint      `gorm:"primaryKey"`
	Symbol      string    `gorm:"type:varchar(20);not null;index"`
	AssetType   string    `gorm:"type:varchar(20);not null"`
	Action      string    `gorm:"type:varchar(10);not null"` // BUY, SELL, HOLD
	Confidence  float64   `gorm:"not null"`
	Price       float64   `gorm:"not null"`
	TargetPrice float64   `gorm:"default:0"`
	StopLoss    float64   `gorm:"default:0"`
	Reasoning   string    `gorm:"type:text"`
	Indicators  string    `gorm:"type:json"` // RSI, MACD, etc.
	ValidUntil  time.Time `gorm:"not null"`
	IsActive    bool      `gorm:"default:true"`
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// AllocationPlan represents AI-generated investment plan
type AllocationPlan struct {
	ID          uint         `gorm:"primaryKey"`
	UserID      uint         `gorm:"not null;index"`
	TotalBudget float64      `gorm:"not null"`
	Allocations []Allocation `gorm:"foreignKey:PlanID;constraint:OnDelete:CASCADE"`
	Strategy    string       `gorm:"type:varchar(50)"` // aggressive, moderate, conservative
	Reasoning   string       `gorm:"type:text"`
	Confidence  float64      `gorm:"not null"`
	ValidUntil  time.Time    `gorm:"not null"`
	IsExecuted  bool         `gorm:"default:false"`
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Allocation represents individual asset allocation in a plan
type Allocation struct {
	ID             uint    `gorm:"primaryKey"`
	PlanID         uint    `gorm:"not null;index"`
	Symbol         string  `gorm:"type:varchar(20);not null"`
	AssetType      string  `gorm:"type:varchar(20);not null"`
	Amount         float64 `gorm:"not null"`
	Percentage     float64 `gorm:"not null"`
	EstimatedUnits float64 `gorm:"not null"`
	CurrentPrice   float64 `gorm:"not null"`
	SignalID       uint    `gorm:"index"`
	Confidence     float64 `gorm:"not null"`
	Reasoning      string  `gorm:"type:text"`
	CreatedAt      time.Time
}

// PriceAlert represents user-defined price alerts
type PriceAlert struct {
	ID            uint      `gorm:"primaryKey"`
	UserID        uint      `gorm:"not null;index"`
	Symbol        string    `gorm:"type:varchar(20);not null"`
	AssetType     string    `gorm:"type:varchar(20);not null"`
	TargetPrice   float64   `gorm:"not null"`
	Condition     string    `gorm:"type:varchar(10);not null"` // above, below
	IsTriggered   bool      `gorm:"default:false"`
	TriggeredAt   *time.Time
	NotifyEmail   bool      `gorm:"default:true"`
	NotifyPush    bool      `gorm:"default:false"`
	NotifySMS     bool      `gorm:"default:false"`
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// NotificationPreference represents user notification settings
type NotificationPreference struct {
	ID               uint   `gorm:"primaryKey"`
	UserID           uint   `gorm:"uniqueIndex;not null"`
	EmailEnabled     bool   `gorm:"default:true"`
	PushEnabled      bool   `gorm:"default:false"`
	SMSEnabled       bool   `gorm:"default:false"`
	PriceAlerts      bool   `gorm:"default:true"`
	SignalAlerts     bool   `gorm:"default:true"`
	PortfolioUpdates bool   `gorm:"default:true"`
	WeeklySummary    bool   `gorm:"default:true"`
	DeviceToken      string `gorm:"type:varchar(255)"` // For push notifications
	PhoneNumber      string `gorm:"type:varchar(20)"`  // For SMS
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// TechnicalIndicator stores calculated technical indicators
type TechnicalIndicator struct {
	ID         uint      `gorm:"primaryKey"`
	Symbol     string    `gorm:"type:varchar(20);not null;index:idx_symbol_indicator_time"`
	Indicator  string    `gorm:"type:varchar(20);not null;index:idx_symbol_indicator_time"` // RSI, MACD, SMA, EMA
	Value      float64   `gorm:"not null"`
	Signal     string    `gorm:"type:varchar(10)"` // bullish, bearish, neutral
	Period     int       `gorm:"not null"`
	Timestamp  time.Time `gorm:"not null;index:idx_symbol_indicator_time"`
	CreatedAt  time.Time
}

// MarketSentiment represents market sentiment analysis
type MarketSentiment struct {
	ID              uint      `gorm:"primaryKey"`
	Symbol          string    `gorm:"type:varchar(20);not null;index"`
	AssetType       string    `gorm:"type:varchar(20);not null"`
	Sentiment       string    `gorm:"type:varchar(20);not null"` // bullish, bearish, neutral
	Score           float64   `gorm:"not null"` // -1 to 1
	FearGreedIndex  int       `gorm:"default:0"` // 0-100
	SocialMentions  int       `gorm:"default:0"`
	NewsScore       float64   `gorm:"default:0"`
	VolumeAnomaly   float64   `gorm:"default:0"`
	Timestamp       time.Time `gorm:"not null"`
	CreatedAt       time.Time
}

// Calculate methods for FinancialProfile
func (fp *FinancialProfile) GetInvestmentBudget() float64 {
	if fp.UseRatio {
		surplus := fp.MonthlyIncome - fp.FixedExpenses
		if surplus <= 0 {
			return 0
		}
		return surplus * fp.InvestmentRatio
	}
	return fp.InvestmentAmount
}

func (fp *FinancialProfile) GetDisposableIncome() float64 {
	return fp.MonthlyIncome - fp.FixedExpenses
}

// Calculate methods for Holding
func (h *Holding) UpdatePnL() {
	h.TotalValue = h.Quantity * h.CurrentPrice
	h.PnL = h.TotalValue - (h.Quantity * h.AvgBuyPrice)
	if h.AvgBuyPrice > 0 {
		h.PnLPercent = (h.PnL / (h.Quantity * h.AvgBuyPrice)) * 100
	}
}
